# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2
[http]
# HTTP server settings

# The IPv4/IPv6 address to bind the HTTP server to.
# Binds to all interfaces by default:
address = "0.0.0.0"

# All IPv6 interfaces:
#address = "::"

# Localhost only:
#address = "127.0.0.1"
#address = "::1"

# The URL of the roomserver that is reachable by internal services
service_url = "https://roomserver.opentalk.test"

# The publicly reachable URL of this server
public_url = "https://roomserver.opentalk.test"

# The api keys for internal service endpoints
#
# The roomserver can have multiple api keys configured. An api key can be configured as string ("<key_id>:<key_secret>")
# or as key/value pair ({id = "<key_id>", secret = "<key_secret>"}).
api_keys = [{ id = "Controller", secret = "QKwu4cYmwisLOU2XyqrWOYEDnap6Nubv" }]

# The port to bind the HTTP server to (defaults to 11333)
#port = 11333

# Disable the OpenAPI endpoint under `/docs/openapi.json` and the corresponding
# swagger endpoint under `/swagger`.
#enable_openapi = false

[controller]
# Controller settings
#
# If not configured, assets and module resources will be saved in memory.

# The URL of the controller
url = "https://controller.opentalk.test"

# The api key for the controllers service API
api_key = { "id" = "Controller", "secret" = "QKwu4cYmwisLOU2XyqrWOYEDnap6Nubv" }
